language: go

sudo: required

before_install:
- sudo ./Vagrantfile.provision.sh

script:
- go test -v ./...
- go build
- cd features && sudo behave _network_contraints.feature

after_success:
- bash <(curl -s https://codecov.io/bash)
