language: go
go: "1.10"

sudo: required
services:
- docker

before_install:
- sudo pip install ansible docker-py dnspython
- rvm use 2

install:
- make install

script:
- make test
- make build
- make specs

after_failure:
- docker logs transprouter_priv_ws
- docker exec -it transprouter_priv_ws ping -c 1 web.public
- docker exec -it transprouter_priv_ws ping -c 1 web.private
- docker exec -it transprouter_priv_ws ping -c 1 proxy.private

after_success:
- bash <(curl -s https://codecov.io/bash)

