language: go
go: "1.10"

sudo: required
services:
- docker

before_install:
- source ~/virtualenv/python3.6/bin/activate
- rvm use 2

install:
- make install

script:
- make test
- make build
- make specs

after_failure:
- docker exec -it transprouter_priv_ws ping -c 1 web.public
- docker exec -it transprouter_priv_ws ping -c 1 web.private
- docker exec -it transprouter_priv_ws ping -c 1 proxy.private
- docker logs transprouter_priv_dns
- docker logs transprouter_priv_proxy
- docker logs transprouter_priv_ws
- docker logs transprouter_priv_web
- docker logs transprouter_priv_ssh
- docker logs transprouter_pub_web
- docker logs transprouter_pub_ssh

after_success:
- bash <(curl -s https://codecov.io/bash)

