language: go

sudo: required
services:
- docker

before_install:
- sudo pip install ansible docker-py dnspython
- rvm use 2

install:
- make install

script:
- make test
- make build
- make specs

after_failure:
- docker logs transprouter_priv_ws

after_success:
- bash <(curl -s https://codecov.io/bash)

