language: go

sudo: required
services:
- docker

before_install:
- echo -e "Host localhost\n    StrictHostKeyChecking no" >> ~/.ssh/config
- docker-compose -f integration-tests/docker/docker-compose.yml -p test up -d --build

before_script:
- docker ps
- for i in $(seq 0 30) ; do sleep 1 && ssh root@localhost -p 2222 true && break ; done

script:
- go test -v ./...
- go build
- scp -p 2222 transprouter transprouter@localhost:/opt/transprouter/transprouter
- bundle exec cucumber
