language: go

sudo: required
services:
- docker

before_install:
- git clone --depth 1 https://github.com/transprouter/integration-tests.git
- docker-compose -f integration-tests/docker/docker-compose.yml -p test up -d --build

before_script:
- docker ps
- for i in $(seq 0 30) ; do sleep 1 && ssh root@localhost -p 2222 -o StrictHostKeyChecking=no true && break ; done
